apiVersion: apps/v1
kind: Deployment
metadata:
  name:  db-noticias-deployment
spec:
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
      - image: aluracursos/mysql-db:1
        name: db-noticias-container
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: db-configmap
  selector:
    matchLabels:
      app: db-noticias
      