apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    app: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: segundo-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: jenkins-container
    image: jenkins/jenkins
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: segundo-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name:  segundo-volume
    hostPath:
      path: /Users/thiagoconstantino/segundo-volume-kubernetes
      type: DirectoryOrCreate

