apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias-container
        image: aluracursos/portal-noticias:1
        resources:
          requests:
            memory: "8Mi"
            cpu: "3m"
          limits:
            memory: "16Mi"
            cpu: "8m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: portal-noticias-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 25
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
