kind: Service
apiVersion: v1
metadata:
  name: svc-sistema-noticias
spec:
  selector:
    app: sistema-noticias
  type: NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80
    nodePort: 30001