kind: Service
apiVersion: v1
metadata:
  name:  svc-pod-1
spec:
  selector:
    app: primeiro-pod
  type:  NodePort
  ports:
  - name:  port-svc-pod-1
    port:  80
    targetPort: 80
    nodePort:  30000